name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Lint Dockerfile
      uses: "jwr0/dockerfile-linter-action"
      secrets:
      - GITHUB_TOKEN
      env:
        DOCKERFILE: "./Dockerfile.docs"
    - name: Build the Docker image
      run: docker build -f Dockerfile.docs . --tag docs:$(date +%s)
