name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: -
          Hey, thank you for the issue. This is an automatic message. I usually answer within a few hours.
          
          I would like to ask you if the problem occurs with a specific page to indicate its address, if you have not provided it yet. This significantly reduces the time to provide assistance.
          
          Sincerely,
